// This file will be auto-generated by Supabase CLI
// For now, we'll create a basic type structure
// Run: npx supabase gen types typescript --project-id "your-project-id" > lib/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          city_id: string | null
          survey_completed: boolean
          membership_tier: 'free' | 'plus' | 'select'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name?: string | null
          city_id?: string | null
          survey_completed?: boolean
          membership_tier?: 'free' | 'plus' | 'select'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          city_id?: string | null
          survey_completed?: boolean
          membership_tier?: 'free' | 'plus' | 'select'
          created_at?: string
          updated_at?: string
        }
      }
      partnerships: {
        Row: {
          id: string
          owner_id: string
          name: string
          status: 'active' | 'pending' | 'inactive'
          city_id: string
          membership_tier: 'free' | 'plus' | 'select'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          status?: 'active' | 'pending' | 'inactive'
          city_id: string
          membership_tier?: 'free' | 'plus' | 'select'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          status?: 'active' | 'pending' | 'inactive'
          city_id?: string
          membership_tier?: 'free' | 'plus' | 'select'
          created_at?: string
          updated_at?: string
        }
      }
      survey_responses: {
        Row: {
          id: string
          user_id: string
          partnership_id: string | null
          responses: Json
          completion_percentage: number
          last_saved_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          partnership_id?: string | null
          responses?: Json
          completion_percentage?: number
          last_saved_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          partnership_id?: string | null
          responses?: Json
          completion_percentage?: number
          last_saved_at?: string
          created_at?: string
          updated_at?: string
        }
      }
      cities: {
        Row: {
          id: string
          name: string
          status: 'live' | 'waitlist'
          zip_codes: string[]
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          status: 'live' | 'waitlist'
          zip_codes: string[]
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          status?: 'live' | 'waitlist'
          zip_codes?: string[]
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      membership_tier: 'free' | 'plus' | 'select'
      city_status: 'live' | 'waitlist'
      partnership_status: 'active' | 'pending' | 'inactive'
    }
  }
}